### ISSUE TITLE
Issue making with minGW

### ISSUE THREAD

**Issue by harrspen** [rspeele/mice#1]
Can't seem to make with minGW. Not sure if you can help!
[Debug.txt](https://github.com/rspeele/MouseMeat/files/2091480/Debug.txt)

**Comment by rspeele** [comment]
Just looking at the log you attached, it seems like the compiler these days catches a lot more shady stuff than it did when I wrote this. A couple warnings in my code, an error in the included mingw mutex code.

Try removing -Wall and adding -fpermissive to CXXFLAGS on line 2 of the Makefile, see if that lets you build.

**Comment by harrspen** [comment]
Sorry for the late reply, been away last week. But that is now building correctly. Many thanks!
